### PR TITLE
Add liblz4-tool package install to the dockerfile

### PR DESCRIPTION
**Pull request by MeanderingCode**
Install liblz4-tool for lz4 and lz4c required to package cyanogenmod images.

### CODE REVIEW

**Comment by stucki** [comment]
Thanks!

**Comment by stucki** [comment]
I have to add thought that my builds run fine without these packages. What device are you building for?

**Comment by MeanderingCode** [comment]
Moto X 2014 Pure Edition XT1095, victara

**Comment by stucki** [comment]
Thanks. Weird that I didn't need it. However, the patch was already merged so nothing more that needs to be done here.

**Pull request merged**
