### PR TITLE
usb privileged version

### PR DESCRIPTION
**Pull request by MichalCz**
Hey,

Perhaps you would be interested in a version that allows usb debugging and connecting an actual device to the docker container.

There's a security drawback - the container must run in privileged mode, which mean it has actual root access and it can't be that trusted. That's why I'm proposing this PR separately to another one I'm pushing simultaneously. If you have an idea on some kind of a switch I could add it later.

Best,
Mike

### CODE REVIEW

**Comment by MichalCz** [comment]
Hey, I'll be developing a little bit here - it seems not running fine any more with screen.

**Comment by stucki** [comment]
Did you know that it's possible to run adb over the network?

```
# On the host, run adb in daemon mode:
sudo adb -a fork-server server

# Inside the container, set an alias for adb (adb is used from the build path)
alias adb='/home/cmbuild/android/out/host/linux-x86/bin/adb -H <ip of your host>'

# Test:
adb devices
```
Works fine for me without any modifications to the Docker image.

However, we could still let users run Docker in privileged mode and forward the USB device. Ok with me, however this should be configurable right from the start. Can you update the PR please?

**Comment by stucki** [comment]
Besides this: The tests in front of `mkdir` don't belong to this change, do they?

**Comment by MichalCz** [comment]
Hey, yes I know you can run adb over network, but that means you need to have adb somehow installed on the host - the beauty of your docker image is that you needn't do that.

Anyway I added a -p / --privileged switch for this. I must check what makes screen not working, so this is not merge-able yet.

**Comment by stucki** [comment]
How about calling the flag `--enable-usb`? As a user, I don't need to know the relation with Dockers privileged mode, so this is otherwise not self-explaining.

Regarding the screen check: How about you're just leaving the line as it was before? No matter what, it's not related to this change, so it should be move into a different PR anyway. And then, this one could be merged right away...

**Comment by MichalCz** [comment]
How about this? :)

**Comment by stucki** [comment]
Thank you!

**Comment by MichalCz** [comment]
Ur welcome. :)

I have a branch that fixes [docker #8755](https://github.com/docker/docker/issues/8755), but I don't think this should be merged to master - docker or ubuntu would fix that sooner or later. For now if anybody needs it, just cherry-pick [my commit 5b769a7c](https://github.com/MichalCz/docker-cyanogenmod/commit/5b769a7c6c42bf9d8ea2314eea110ce352463349).

**Comment by stucki** [comment]
Can you please take a look at https://github.com/stucki/docker-cyanogenmod/commit/6b6aba0a9329dc3d8dbb377c4f63595ec4e44bb1 + https://github.com/stucki/docker-cyanogenmod/commit/cfd61745106734a1b82f6c145900b4d5cf99ca08
I remember that I fixed a thing like this in the past, however I thought it was fixed, couldn't reproduce this with my Ubuntu 14.04.
In any case it would be good to create a new ticket if this is still needed. Therefore, I'm closing here.

**Pull request merged**
